### ISSUE TITLE
Component: Game Page

### ISSUE THREAD

**Issue by sloorush** [r-ush/tic-tac-toe-react#10]
<h1>Can only be done after Component: Board is made</h1>

**Please describe the feature you want this project to offer**
Beautiful UI for the game page.

**Describe the solution you'd like**
Show the board,  add restart buttons, show player names, and show which players turn it is

**Comment by sejalshri** [comment]
@r-ush  ,i would like to work on this issue.

**Comment by sloorush** [comment]
One can only work on it when Board and Square components are made, would you like to contribute on those? @sejalshri

**Comment by sejalshri** [comment]
yaa,sure .If it is not yet assigned,i would love to contribute.

**Comment by sloorush** [comment]
Yes, Leave a comment on the Issue you want to work on @sejalshri
