### ISSUE TITLE
Add logic for Game page

### ISSUE THREAD

**Issue by sloorush** [r-ush/tic-tac-toe-react#11]
<h1>Can only be done after calculate winner function is made in helper.js file</h1>

**Please describe the feature you want this project to offer**
Add Logic for Game Page

**Describe the solution you'd like**
The game page should have various states like declaring the turn and calculating winners.

**Comment by shakti97** [comment]
I would like to work on this @r-ush

**Comment by sloorush** [comment]
Sure you can take it up @shakti97

**Comment by cyberquill** [comment]
Hi @r-ush can I take up this issue?

**Comment by sloorush** [comment]
Hey @brij1999, You can take it up!
