### ISSUE TITLE
add favicon

### ISSUE THREAD

**Issue by sloorush** [r-ush/tic-tac-toe-react#12]
**Please describe the feature you want this project to offer**
Favicon contains Create React app image, change it to something related to the project

**Describe the solution you'd like**
A cool logo for the project

**Comment by pratyaksh123** [comment]
I'll do it

**Comment by Akhil-chaudhary** [comment]
I will be creating a logo for the game.

**Comment by sloorush** [comment]
This issue is already resolved, you can work on it if you feel yours is an improvement @Akhil-chaudhary
