### ISSUE TITLE
Add Redux support and Routing to the app

### ISSUE THREAD

**Issue by cyberquill** [r-ush/tic-tac-toe-react#18]
**Please describe the feature you want this project to offer**
I would like to work on the implementation of routing and redux for the application. 

**Describe the solution you'd like**
Adding Redux to the app would allow the components to effectively communicate with each other with ease. Also, as the app progresses, it would need routing support to enable effective navigation. I would be using a react-hook based approach for both the implementations, and use the prescribed code practices.

**Describe alternatives you've considered (Optional)**

**Additional context (Optional)**

**Comment by sloorush** [comment]
Hey @brij1999, I don't think redux support is needed for this app, but it is cool if you're adding it, you can go about adding the routing to it! Good luck!

**Comment by cyberquill** [comment]
So just to be clear, I should add routing, and redux is optional. Correct?
