### ISSUE TITLE
Logic to calculate winner

### ISSUE THREAD

**Issue by sloorush** [r-ush/tic-tac-toe-react#3]
**Please describe the feature you want this project to offer**
Add Logic for calculating winner in Helpers.js 

**Describe the solution you'd like**
Make a function that checks the conditions of winning with the situation of the game 

**Additional context (Optional)**
Refer to how a tic-tac-toe game works, and how it can be implemented using arrays in js.

**Comment by i-aryan** [comment]
Hey. I would like to work on it. I'll get the logic done.

**Comment by sloorush** [comment]
Sure, you can go ahead! @i-aryan

**Comment by sloorush** [comment]
Hi @i-aryan What is the update?

**Comment by i-aryan** [comment]
Hey, I'll do it by tomorrow. I had to travel today.

**Comment by i-aryan** [comment]
Open to anyone else. I got univ tests all of a sudden. Sorry.

**Comment by cyberquill** [comment]
Hi @r-ush I would like to take this

**Comment by sloorush** [comment]
Hey @brij1999, You can take it up! Good luck!
