### ISSUE TITLE
Component: Board

### ISSUE THREAD

**Issue by sloorush** [r-ush/tic-tac-toe-react#8]
<h1>Can only be done after Component: Square is made</h1>

**Please describe the feature you want this project to offer**
Make a UI for the board on which the game will be played on

**Describe the solution you'd like**
Mapping 9 square components in the fashion of a tic tac toe board will be apt

**Comment by EC7495** [comment]
Hi, I can start setting this up while the square component is made.

**Comment by sloorush** [comment]
Yes, You can start! @EC7495
